###############################################################################
##  Name:   Dockerfile
##  Date:   2018-01-15
##  Developer:  Chris Page
##  Email:  phriscage@gmail.com
##  Purpose:   This Dockerfile contains the Beers Review xample
################################################################################
## build stage
FROM golang:1.9.2-alpine3.7 AS build-env

# Set the file maintainer (your name - the file's author)
MAINTAINER Chris Page <phriscage@gmail.com>

# app working directory
WORKDIR /app

# Install Git, Go dependencies, and build the app
RUN apk --no-cache add --virtual git && \
        rm -rf /var/cache/apk/*

# Pull the Go dependencies
RUN go get github.com/pilu/fresh && \
        go get -d -v \
        # specify individually to avoid rebuilding container layer during dev
        github.com/olivere/elastic \
        github.com/gorilla/handlers \
        github.com/sirupsen/logrus \
        github.com/gorilla/mux \
        github.com/fatih/structs

# Add the sample data
COPY data /app/data

# Add the application
COPY *.go ./

# Build the package
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /app/main .

EXPOSE 8080

ENTRYPOINT ["/app/main"]
